version: "3"


services:
  server:
    image: nycookie/sn1054bot:latest
    container_name: sn1054bot
    environment:
      - NODE_ENV=
      - TOKEN=
      - Mailpw=
      - Mailadress=
      - MyMailadress=
      - Password=
      - DB=
      - DBConnectionstring=
      - clientid =
      - guildId = 

    restart: always
